opt_in_rules:
- empty_count
# - missing_docs

disabled_rules:
- vertical_whitespace # Turn off until configurable to 2 newlines

included:
- Sources

excluded:
- Carthage
- Sources/Constants

line_length: 200
